version: '3.8'

services:
  invoice-generator:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Mount external directories for data persistence
      - ./invoices:/app/invoices
      - ./db.sqlite:/app/db.sqlite
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Development version with hot reload
  invoice-generator-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - ./invoices:/app/invoices
      - ./db.sqlite:/app/db.sqlite
    command: npm run dev:backend
    profiles:
      - dev